site_name: cathedral

nav:
    - Home: index.md

theme: readthedocs

repo_url: https://github.com/tetris-hermetris/cathedral

site_description: This is the documentation site for cathedral.

site_author: Max Ilinov
